### ISSUE TITLE
Problema icona su iOS

### ISSUE THREAD

**Issue by Andrea-Canale** [ittagnelli/snAcks#13]
Su iOS l'icona della PWA non viene visualizzata correttamente a causa del seguente errore:

![image](https://user-images.githubusercontent.com/99402143/161332974-c38c8d83-f620-4606-a962-75056280acb5.png)

**Comment by mancusoa74** [comment]
solo in modalità dev.
in produzione tutto ok.

come vedi localhost:3000/snacks non esiste in locale

ti propongo di chiudere il bug quindi
