### ISSUE TITLE
delete snacks directory content before upload from pipeline

### ISSUE THREAD

**Issue by mancusoa74** [ittagnelli/snAcks#67]
E' necessario modificare la pipeline CI/CD in modo che cancelli il contenuto della directory snacks dal web server prima di fare l'upload dell'applicazione

Questo è necessario per l'aggiornamento dell'applicazione PWA

**Comment by Andrea-Canale** [comment]
Pull request: #72

**Comment by mancusoa74** [comment]
bene

grazie

**Comment by mancusoa74** [comment]
ci sono ancora problemi, non funziona

ho provato a guardarla,sembra tutto ok ma non funziona

**Comment by Andrea-Canale** [comment]
Mi sa che serve questo argomento sia sul comando SCP che su quello del SSH:-o StrictHostKeyChecking=no

**Comment by mancusoa74** [comment]
ho modificato in modo che svuoti solo la directory e non rimuova la directory
