### ISSUE TITLE
creare una TAB About o Info

### ISSUE THREAD

**Issue by mancusoa74** [ittagnelli/snAcks#8]
creare una tab aggiuntiva con informazioni tipiche di about o info

inserisci che è stato sviluppato per ATS da me e te

Inserire il logo di ATS (espedix)

**Comment by Andrea-Canale** [comment]
Abbiamo bisogno anche di una privacy policy?

**Comment by Andrea-Canale** [comment]
Una prima versione dell'about page.
https://github.com/ittagnelli/snAcks/tree/feature/about

**Comment by mancusoa74** [comment]
fixed
